// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: imu.proto
// Protobuf Java Version: 4.34.1

package ru.skatelab.capture.proto;

public final class Imu {
  private Imu() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMUSampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skatelab.capture.IMUSample)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint64 timestamp_ns = 1;</code>
     * @return The timestampNs.
     */
    long getTimestampNs();

    /**
     * <code>float acc_x = 2;</code>
     * @return The accX.
     */
    float getAccX();

    /**
     * <code>float acc_y = 3;</code>
     * @return The accY.
     */
    float getAccY();

    /**
     * <code>float acc_z = 4;</code>
     * @return The accZ.
     */
    float getAccZ();

    /**
     * <code>float gyro_x = 5;</code>
     * @return The gyroX.
     */
    float getGyroX();

    /**
     * <code>float gyro_y = 6;</code>
     * @return The gyroY.
     */
    float getGyroY();

    /**
     * <code>float gyro_z = 7;</code>
     * @return The gyroZ.
     */
    float getGyroZ();

    /**
     * <code>float quat_w = 8;</code>
     * @return The quatW.
     */
    float getQuatW();

    /**
     * <code>float quat_x = 9;</code>
     * @return The quatX.
     */
    float getQuatX();

    /**
     * <code>float quat_y = 10;</code>
     * @return The quatY.
     */
    float getQuatY();

    /**
     * <code>float quat_z = 11;</code>
     * @return The quatZ.
     */
    float getQuatZ();
  }
  /**
   * Protobuf type {@code skatelab.capture.IMUSample}
   */
  public  static final class IMUSample extends
      com.google.protobuf.GeneratedMessageLite<
          IMUSample, IMUSample.Builder> implements
      // @@protoc_insertion_point(message_implements:skatelab.capture.IMUSample)
      IMUSampleOrBuilder {
    private IMUSample() {
    }
    public static final int TIMESTAMP_NS_FIELD_NUMBER = 1;
    private long timestampNs_;
    /**
     * <code>uint64 timestamp_ns = 1;</code>
     * @return The timestampNs.
     */
    @java.lang.Override
    public long getTimestampNs() {
      return timestampNs_;
    }
    /**
     * <code>uint64 timestamp_ns = 1;</code>
     * @param value The timestampNs to set.
     */
    private void setTimestampNs(long value) {
      
      timestampNs_ = value;
    }
    /**
     * <code>uint64 timestamp_ns = 1;</code>
     */
    private void clearTimestampNs() {

      timestampNs_ = 0L;
    }

    public static final int ACC_X_FIELD_NUMBER = 2;
    private float accX_;
    /**
     * <code>float acc_x = 2;</code>
     * @return The accX.
     */
    @java.lang.Override
    public float getAccX() {
      return accX_;
    }
    /**
     * <code>float acc_x = 2;</code>
     * @param value The accX to set.
     */
    private void setAccX(float value) {
      
      accX_ = value;
    }
    /**
     * <code>float acc_x = 2;</code>
     */
    private void clearAccX() {

      accX_ = 0F;
    }

    public static final int ACC_Y_FIELD_NUMBER = 3;
    private float accY_;
    /**
     * <code>float acc_y = 3;</code>
     * @return The accY.
     */
    @java.lang.Override
    public float getAccY() {
      return accY_;
    }
    /**
     * <code>float acc_y = 3;</code>
     * @param value The accY to set.
     */
    private void setAccY(float value) {
      
      accY_ = value;
    }
    /**
     * <code>float acc_y = 3;</code>
     */
    private void clearAccY() {

      accY_ = 0F;
    }

    public static final int ACC_Z_FIELD_NUMBER = 4;
    private float accZ_;
    /**
     * <code>float acc_z = 4;</code>
     * @return The accZ.
     */
    @java.lang.Override
    public float getAccZ() {
      return accZ_;
    }
    /**
     * <code>float acc_z = 4;</code>
     * @param value The accZ to set.
     */
    private void setAccZ(float value) {
      
      accZ_ = value;
    }
    /**
     * <code>float acc_z = 4;</code>
     */
    private void clearAccZ() {

      accZ_ = 0F;
    }

    public static final int GYRO_X_FIELD_NUMBER = 5;
    private float gyroX_;
    /**
     * <code>float gyro_x = 5;</code>
     * @return The gyroX.
     */
    @java.lang.Override
    public float getGyroX() {
      return gyroX_;
    }
    /**
     * <code>float gyro_x = 5;</code>
     * @param value The gyroX to set.
     */
    private void setGyroX(float value) {
      
      gyroX_ = value;
    }
    /**
     * <code>float gyro_x = 5;</code>
     */
    private void clearGyroX() {

      gyroX_ = 0F;
    }

    public static final int GYRO_Y_FIELD_NUMBER = 6;
    private float gyroY_;
    /**
     * <code>float gyro_y = 6;</code>
     * @return The gyroY.
     */
    @java.lang.Override
    public float getGyroY() {
      return gyroY_;
    }
    /**
     * <code>float gyro_y = 6;</code>
     * @param value The gyroY to set.
     */
    private void setGyroY(float value) {
      
      gyroY_ = value;
    }
    /**
     * <code>float gyro_y = 6;</code>
     */
    private void clearGyroY() {

      gyroY_ = 0F;
    }

    public static final int GYRO_Z_FIELD_NUMBER = 7;
    private float gyroZ_;
    /**
     * <code>float gyro_z = 7;</code>
     * @return The gyroZ.
     */
    @java.lang.Override
    public float getGyroZ() {
      return gyroZ_;
    }
    /**
     * <code>float gyro_z = 7;</code>
     * @param value The gyroZ to set.
     */
    private void setGyroZ(float value) {
      
      gyroZ_ = value;
    }
    /**
     * <code>float gyro_z = 7;</code>
     */
    private void clearGyroZ() {

      gyroZ_ = 0F;
    }

    public static final int QUAT_W_FIELD_NUMBER = 8;
    private float quatW_;
    /**
     * <code>float quat_w = 8;</code>
     * @return The quatW.
     */
    @java.lang.Override
    public float getQuatW() {
      return quatW_;
    }
    /**
     * <code>float quat_w = 8;</code>
     * @param value The quatW to set.
     */
    private void setQuatW(float value) {
      
      quatW_ = value;
    }
    /**
     * <code>float quat_w = 8;</code>
     */
    private void clearQuatW() {

      quatW_ = 0F;
    }

    public static final int QUAT_X_FIELD_NUMBER = 9;
    private float quatX_;
    /**
     * <code>float quat_x = 9;</code>
     * @return The quatX.
     */
    @java.lang.Override
    public float getQuatX() {
      return quatX_;
    }
    /**
     * <code>float quat_x = 9;</code>
     * @param value The quatX to set.
     */
    private void setQuatX(float value) {
      
      quatX_ = value;
    }
    /**
     * <code>float quat_x = 9;</code>
     */
    private void clearQuatX() {

      quatX_ = 0F;
    }

    public static final int QUAT_Y_FIELD_NUMBER = 10;
    private float quatY_;
    /**
     * <code>float quat_y = 10;</code>
     * @return The quatY.
     */
    @java.lang.Override
    public float getQuatY() {
      return quatY_;
    }
    /**
     * <code>float quat_y = 10;</code>
     * @param value The quatY to set.
     */
    private void setQuatY(float value) {
      
      quatY_ = value;
    }
    /**
     * <code>float quat_y = 10;</code>
     */
    private void clearQuatY() {

      quatY_ = 0F;
    }

    public static final int QUAT_Z_FIELD_NUMBER = 11;
    private float quatZ_;
    /**
     * <code>float quat_z = 11;</code>
     * @return The quatZ.
     */
    @java.lang.Override
    public float getQuatZ() {
      return quatZ_;
    }
    /**
     * <code>float quat_z = 11;</code>
     * @param value The quatZ to set.
     */
    private void setQuatZ(float value) {
      
      quatZ_ = value;
    }
    /**
     * <code>float quat_z = 11;</code>
     */
    private void clearQuatZ() {

      quatZ_ = 0F;
    }

    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static ru.skatelab.capture.proto.Imu.IMUSample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static ru.skatelab.capture.proto.Imu.IMUSample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ru.skatelab.capture.proto.Imu.IMUSample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ru.skatelab.capture.proto.Imu.IMUSample prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code skatelab.capture.IMUSample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ru.skatelab.capture.proto.Imu.IMUSample, Builder> implements
        // @@protoc_insertion_point(builder_implements:skatelab.capture.IMUSample)
        ru.skatelab.capture.proto.Imu.IMUSampleOrBuilder {
      // Construct using ru.skatelab.capture.proto.Imu.IMUSample.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint64 timestamp_ns = 1;</code>
       * @return The timestampNs.
       */
      @java.lang.Override
      public long getTimestampNs() {
        return instance.getTimestampNs();
      }
      /**
       * <code>uint64 timestamp_ns = 1;</code>
       * @param value The timestampNs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampNs(long value) {
        copyOnWrite();
        instance.setTimestampNs(value);
        return this;
      }
      /**
       * <code>uint64 timestamp_ns = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampNs() {
        copyOnWrite();
        instance.clearTimestampNs();
        return this;
      }

      /**
       * <code>float acc_x = 2;</code>
       * @return The accX.
       */
      @java.lang.Override
      public float getAccX() {
        return instance.getAccX();
      }
      /**
       * <code>float acc_x = 2;</code>
       * @param value The accX to set.
       * @return This builder for chaining.
       */
      public Builder setAccX(float value) {
        copyOnWrite();
        instance.setAccX(value);
        return this;
      }
      /**
       * <code>float acc_x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccX() {
        copyOnWrite();
        instance.clearAccX();
        return this;
      }

      /**
       * <code>float acc_y = 3;</code>
       * @return The accY.
       */
      @java.lang.Override
      public float getAccY() {
        return instance.getAccY();
      }
      /**
       * <code>float acc_y = 3;</code>
       * @param value The accY to set.
       * @return This builder for chaining.
       */
      public Builder setAccY(float value) {
        copyOnWrite();
        instance.setAccY(value);
        return this;
      }
      /**
       * <code>float acc_y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccY() {
        copyOnWrite();
        instance.clearAccY();
        return this;
      }

      /**
       * <code>float acc_z = 4;</code>
       * @return The accZ.
       */
      @java.lang.Override
      public float getAccZ() {
        return instance.getAccZ();
      }
      /**
       * <code>float acc_z = 4;</code>
       * @param value The accZ to set.
       * @return This builder for chaining.
       */
      public Builder setAccZ(float value) {
        copyOnWrite();
        instance.setAccZ(value);
        return this;
      }
      /**
       * <code>float acc_z = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccZ() {
        copyOnWrite();
        instance.clearAccZ();
        return this;
      }

      /**
       * <code>float gyro_x = 5;</code>
       * @return The gyroX.
       */
      @java.lang.Override
      public float getGyroX() {
        return instance.getGyroX();
      }
      /**
       * <code>float gyro_x = 5;</code>
       * @param value The gyroX to set.
       * @return This builder for chaining.
       */
      public Builder setGyroX(float value) {
        copyOnWrite();
        instance.setGyroX(value);
        return this;
      }
      /**
       * <code>float gyro_x = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGyroX() {
        copyOnWrite();
        instance.clearGyroX();
        return this;
      }

      /**
       * <code>float gyro_y = 6;</code>
       * @return The gyroY.
       */
      @java.lang.Override
      public float getGyroY() {
        return instance.getGyroY();
      }
      /**
       * <code>float gyro_y = 6;</code>
       * @param value The gyroY to set.
       * @return This builder for chaining.
       */
      public Builder setGyroY(float value) {
        copyOnWrite();
        instance.setGyroY(value);
        return this;
      }
      /**
       * <code>float gyro_y = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGyroY() {
        copyOnWrite();
        instance.clearGyroY();
        return this;
      }

      /**
       * <code>float gyro_z = 7;</code>
       * @return The gyroZ.
       */
      @java.lang.Override
      public float getGyroZ() {
        return instance.getGyroZ();
      }
      /**
       * <code>float gyro_z = 7;</code>
       * @param value The gyroZ to set.
       * @return This builder for chaining.
       */
      public Builder setGyroZ(float value) {
        copyOnWrite();
        instance.setGyroZ(value);
        return this;
      }
      /**
       * <code>float gyro_z = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGyroZ() {
        copyOnWrite();
        instance.clearGyroZ();
        return this;
      }

      /**
       * <code>float quat_w = 8;</code>
       * @return The quatW.
       */
      @java.lang.Override
      public float getQuatW() {
        return instance.getQuatW();
      }
      /**
       * <code>float quat_w = 8;</code>
       * @param value The quatW to set.
       * @return This builder for chaining.
       */
      public Builder setQuatW(float value) {
        copyOnWrite();
        instance.setQuatW(value);
        return this;
      }
      /**
       * <code>float quat_w = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuatW() {
        copyOnWrite();
        instance.clearQuatW();
        return this;
      }

      /**
       * <code>float quat_x = 9;</code>
       * @return The quatX.
       */
      @java.lang.Override
      public float getQuatX() {
        return instance.getQuatX();
      }
      /**
       * <code>float quat_x = 9;</code>
       * @param value The quatX to set.
       * @return This builder for chaining.
       */
      public Builder setQuatX(float value) {
        copyOnWrite();
        instance.setQuatX(value);
        return this;
      }
      /**
       * <code>float quat_x = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuatX() {
        copyOnWrite();
        instance.clearQuatX();
        return this;
      }

      /**
       * <code>float quat_y = 10;</code>
       * @return The quatY.
       */
      @java.lang.Override
      public float getQuatY() {
        return instance.getQuatY();
      }
      /**
       * <code>float quat_y = 10;</code>
       * @param value The quatY to set.
       * @return This builder for chaining.
       */
      public Builder setQuatY(float value) {
        copyOnWrite();
        instance.setQuatY(value);
        return this;
      }
      /**
       * <code>float quat_y = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuatY() {
        copyOnWrite();
        instance.clearQuatY();
        return this;
      }

      /**
       * <code>float quat_z = 11;</code>
       * @return The quatZ.
       */
      @java.lang.Override
      public float getQuatZ() {
        return instance.getQuatZ();
      }
      /**
       * <code>float quat_z = 11;</code>
       * @param value The quatZ to set.
       * @return This builder for chaining.
       */
      public Builder setQuatZ(float value) {
        copyOnWrite();
        instance.setQuatZ(value);
        return this;
      }
      /**
       * <code>float quat_z = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuatZ() {
        copyOnWrite();
        instance.clearQuatZ();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:skatelab.capture.IMUSample)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ru.skatelab.capture.proto.Imu.IMUSample();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestampNs_",
              "accX_",
              "accY_",
              "accZ_",
              "gyroX_",
              "gyroY_",
              "gyroZ_",
              "quatW_",
              "quatX_",
              "quatY_",
              "quatZ_",
            };
            java.lang.String info =
                "\u0000\u000b\u0000\u0000\u0001\u000b\u000b\u0000\u0000\u0000\u0001\u0003\u0002\u0001" +
                "\u0003\u0001\u0004\u0001\u0005\u0001\u0006\u0001\u0007\u0001\b\u0001\t\u0001\n\u0001" +
                "\u000b\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ru.skatelab.capture.proto.Imu.IMUSample> parser = PARSER;
          if (parser == null) {
            synchronized (ru.skatelab.capture.proto.Imu.IMUSample.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ru.skatelab.capture.proto.Imu.IMUSample>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:skatelab.capture.IMUSample)
    private static final ru.skatelab.capture.proto.Imu.IMUSample DEFAULT_INSTANCE;
    static {
      IMUSample defaultInstance = new IMUSample();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IMUSample.class, defaultInstance);
    }

    public static ru.skatelab.capture.proto.Imu.IMUSample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMUSample> PARSER;

    public static com.google.protobuf.Parser<IMUSample> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface IMUGapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skatelab.capture.IMUGap)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint64 last_sample_ns = 1;</code>
     * @return The lastSampleNs.
     */
    long getLastSampleNs();

    /**
     * <code>uint64 first_sample_ns = 2;</code>
     * @return The firstSampleNs.
     */
    long getFirstSampleNs();

    /**
     * <code>uint32 reconnect_seq = 3;</code>
     * @return The reconnectSeq.
     */
    int getReconnectSeq();
  }
  /**
   * Protobuf type {@code skatelab.capture.IMUGap}
   */
  public  static final class IMUGap extends
      com.google.protobuf.GeneratedMessageLite<
          IMUGap, IMUGap.Builder> implements
      // @@protoc_insertion_point(message_implements:skatelab.capture.IMUGap)
      IMUGapOrBuilder {
    private IMUGap() {
    }
    public static final int LAST_SAMPLE_NS_FIELD_NUMBER = 1;
    private long lastSampleNs_;
    /**
     * <code>uint64 last_sample_ns = 1;</code>
     * @return The lastSampleNs.
     */
    @java.lang.Override
    public long getLastSampleNs() {
      return lastSampleNs_;
    }
    /**
     * <code>uint64 last_sample_ns = 1;</code>
     * @param value The lastSampleNs to set.
     */
    private void setLastSampleNs(long value) {
      
      lastSampleNs_ = value;
    }
    /**
     * <code>uint64 last_sample_ns = 1;</code>
     */
    private void clearLastSampleNs() {

      lastSampleNs_ = 0L;
    }

    public static final int FIRST_SAMPLE_NS_FIELD_NUMBER = 2;
    private long firstSampleNs_;
    /**
     * <code>uint64 first_sample_ns = 2;</code>
     * @return The firstSampleNs.
     */
    @java.lang.Override
    public long getFirstSampleNs() {
      return firstSampleNs_;
    }
    /**
     * <code>uint64 first_sample_ns = 2;</code>
     * @param value The firstSampleNs to set.
     */
    private void setFirstSampleNs(long value) {
      
      firstSampleNs_ = value;
    }
    /**
     * <code>uint64 first_sample_ns = 2;</code>
     */
    private void clearFirstSampleNs() {

      firstSampleNs_ = 0L;
    }

    public static final int RECONNECT_SEQ_FIELD_NUMBER = 3;
    private int reconnectSeq_;
    /**
     * <code>uint32 reconnect_seq = 3;</code>
     * @return The reconnectSeq.
     */
    @java.lang.Override
    public int getReconnectSeq() {
      return reconnectSeq_;
    }
    /**
     * <code>uint32 reconnect_seq = 3;</code>
     * @param value The reconnectSeq to set.
     */
    private void setReconnectSeq(int value) {
      
      reconnectSeq_ = value;
    }
    /**
     * <code>uint32 reconnect_seq = 3;</code>
     */
    private void clearReconnectSeq() {

      reconnectSeq_ = 0;
    }

    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static ru.skatelab.capture.proto.Imu.IMUGap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static ru.skatelab.capture.proto.Imu.IMUGap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ru.skatelab.capture.proto.Imu.IMUGap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ru.skatelab.capture.proto.Imu.IMUGap prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code skatelab.capture.IMUGap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ru.skatelab.capture.proto.Imu.IMUGap, Builder> implements
        // @@protoc_insertion_point(builder_implements:skatelab.capture.IMUGap)
        ru.skatelab.capture.proto.Imu.IMUGapOrBuilder {
      // Construct using ru.skatelab.capture.proto.Imu.IMUGap.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint64 last_sample_ns = 1;</code>
       * @return The lastSampleNs.
       */
      @java.lang.Override
      public long getLastSampleNs() {
        return instance.getLastSampleNs();
      }
      /**
       * <code>uint64 last_sample_ns = 1;</code>
       * @param value The lastSampleNs to set.
       * @return This builder for chaining.
       */
      public Builder setLastSampleNs(long value) {
        copyOnWrite();
        instance.setLastSampleNs(value);
        return this;
      }
      /**
       * <code>uint64 last_sample_ns = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastSampleNs() {
        copyOnWrite();
        instance.clearLastSampleNs();
        return this;
      }

      /**
       * <code>uint64 first_sample_ns = 2;</code>
       * @return The firstSampleNs.
       */
      @java.lang.Override
      public long getFirstSampleNs() {
        return instance.getFirstSampleNs();
      }
      /**
       * <code>uint64 first_sample_ns = 2;</code>
       * @param value The firstSampleNs to set.
       * @return This builder for chaining.
       */
      public Builder setFirstSampleNs(long value) {
        copyOnWrite();
        instance.setFirstSampleNs(value);
        return this;
      }
      /**
       * <code>uint64 first_sample_ns = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstSampleNs() {
        copyOnWrite();
        instance.clearFirstSampleNs();
        return this;
      }

      /**
       * <code>uint32 reconnect_seq = 3;</code>
       * @return The reconnectSeq.
       */
      @java.lang.Override
      public int getReconnectSeq() {
        return instance.getReconnectSeq();
      }
      /**
       * <code>uint32 reconnect_seq = 3;</code>
       * @param value The reconnectSeq to set.
       * @return This builder for chaining.
       */
      public Builder setReconnectSeq(int value) {
        copyOnWrite();
        instance.setReconnectSeq(value);
        return this;
      }
      /**
       * <code>uint32 reconnect_seq = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReconnectSeq() {
        copyOnWrite();
        instance.clearReconnectSeq();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:skatelab.capture.IMUGap)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ru.skatelab.capture.proto.Imu.IMUGap();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "lastSampleNs_",
              "firstSampleNs_",
              "reconnectSeq_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0003\u0002\u0003" +
                "\u0003\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ru.skatelab.capture.proto.Imu.IMUGap> parser = PARSER;
          if (parser == null) {
            synchronized (ru.skatelab.capture.proto.Imu.IMUGap.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ru.skatelab.capture.proto.Imu.IMUGap>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:skatelab.capture.IMUGap)
    private static final ru.skatelab.capture.proto.Imu.IMUGap DEFAULT_INSTANCE;
    static {
      IMUGap defaultInstance = new IMUGap();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IMUGap.class, defaultInstance);
    }

    public static ru.skatelab.capture.proto.Imu.IMUGap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMUGap> PARSER;

    public static com.google.protobuf.Parser<IMUGap> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface IMURecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skatelab.capture.IMURecord)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.skatelab.capture.IMUSample sample = 1;</code>
     * @return Whether the sample field is set.
     */
    boolean hasSample();
    /**
     * <code>.skatelab.capture.IMUSample sample = 1;</code>
     * @return The sample.
     */
    ru.skatelab.capture.proto.Imu.IMUSample getSample();

    /**
     * <code>.skatelab.capture.IMUGap gap = 2;</code>
     * @return Whether the gap field is set.
     */
    boolean hasGap();
    /**
     * <code>.skatelab.capture.IMUGap gap = 2;</code>
     * @return The gap.
     */
    ru.skatelab.capture.proto.Imu.IMUGap getGap();

    public ru.skatelab.capture.proto.Imu.IMURecord.RecordCase getRecordCase();
  }
  /**
   * Protobuf type {@code skatelab.capture.IMURecord}
   */
  public  static final class IMURecord extends
      com.google.protobuf.GeneratedMessageLite<
          IMURecord, IMURecord.Builder> implements
      // @@protoc_insertion_point(message_implements:skatelab.capture.IMURecord)
      IMURecordOrBuilder {
    private IMURecord() {
    }
    private int recordCase_ = 0;
    private java.lang.Object record_;
    public enum RecordCase
        implements com.google.protobuf.AbstractMessageLite.InternalOneOfEnum {
      SAMPLE(1),
      GAP(2),
      RECORD_NOT_SET(0);
      private final int value;
      private RecordCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RecordCase valueOf(int value) {
        return forNumber(value);
      }

      public static RecordCase forNumber(int value) {
        switch (value) {
          case 1: return SAMPLE;
          case 2: return GAP;
          case 0: return RECORD_NOT_SET;
          default: return null;
        }
      }
      @java.lang.Override public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public RecordCase
    getRecordCase() {
      return RecordCase.forNumber(
          recordCase_);
    }

    private void clearRecord() {
      recordCase_ = 0;
      record_ = null;
    }

    public static final int SAMPLE_FIELD_NUMBER = 1;
    /**
     * <code>.skatelab.capture.IMUSample sample = 1;</code>
     */
    @java.lang.Override
    public boolean hasSample() {
      return recordCase_ == 1;
    }
    /**
     * <code>.skatelab.capture.IMUSample sample = 1;</code>
     */
    @java.lang.Override
    public ru.skatelab.capture.proto.Imu.IMUSample getSample() {
      if (recordCase_ == 1) {
         return (ru.skatelab.capture.proto.Imu.IMUSample) record_;
      }
      return ru.skatelab.capture.proto.Imu.IMUSample.getDefaultInstance();
    }
    /**
     * <code>.skatelab.capture.IMUSample sample = 1;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setSample(ru.skatelab.capture.proto.Imu.IMUSample value) {
      value.getClass();  // minimal bytecode null check
      record_ = value;
      recordCase_ = 1;
    }
    /**
     * <code>.skatelab.capture.IMUSample sample = 1;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void mergeSample(ru.skatelab.capture.proto.Imu.IMUSample value) {
      value.getClass();  // minimal bytecode null check
      if (recordCase_ == 1 &&
          record_ != ru.skatelab.capture.proto.Imu.IMUSample.getDefaultInstance()) {
        record_ = ru.skatelab.capture.proto.Imu.IMUSample.newBuilder((ru.skatelab.capture.proto.Imu.IMUSample) record_)
            .mergeFrom(value).buildPartial();
      } else {
        record_ = value;
      }
      recordCase_ = 1;
    }
    /**
     * <code>.skatelab.capture.IMUSample sample = 1;</code>
     */
    private void clearSample() {
      if (recordCase_ == 1) {
        recordCase_ = 0;
        record_ = null;
      }
    }

    public static final int GAP_FIELD_NUMBER = 2;
    /**
     * <code>.skatelab.capture.IMUGap gap = 2;</code>
     */
    @java.lang.Override
    public boolean hasGap() {
      return recordCase_ == 2;
    }
    /**
     * <code>.skatelab.capture.IMUGap gap = 2;</code>
     */
    @java.lang.Override
    public ru.skatelab.capture.proto.Imu.IMUGap getGap() {
      if (recordCase_ == 2) {
         return (ru.skatelab.capture.proto.Imu.IMUGap) record_;
      }
      return ru.skatelab.capture.proto.Imu.IMUGap.getDefaultInstance();
    }
    /**
     * <code>.skatelab.capture.IMUGap gap = 2;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setGap(ru.skatelab.capture.proto.Imu.IMUGap value) {
      value.getClass();  // minimal bytecode null check
      record_ = value;
      recordCase_ = 2;
    }
    /**
     * <code>.skatelab.capture.IMUGap gap = 2;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void mergeGap(ru.skatelab.capture.proto.Imu.IMUGap value) {
      value.getClass();  // minimal bytecode null check
      if (recordCase_ == 2 &&
          record_ != ru.skatelab.capture.proto.Imu.IMUGap.getDefaultInstance()) {
        record_ = ru.skatelab.capture.proto.Imu.IMUGap.newBuilder((ru.skatelab.capture.proto.Imu.IMUGap) record_)
            .mergeFrom(value).buildPartial();
      } else {
        record_ = value;
      }
      recordCase_ = 2;
    }
    /**
     * <code>.skatelab.capture.IMUGap gap = 2;</code>
     */
    private void clearGap() {
      if (recordCase_ == 2) {
        recordCase_ = 0;
        record_ = null;
      }
    }

    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static ru.skatelab.capture.proto.Imu.IMURecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static ru.skatelab.capture.proto.Imu.IMURecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ru.skatelab.capture.proto.Imu.IMURecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ru.skatelab.capture.proto.Imu.IMURecord prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code skatelab.capture.IMURecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ru.skatelab.capture.proto.Imu.IMURecord, Builder> implements
        // @@protoc_insertion_point(builder_implements:skatelab.capture.IMURecord)
        ru.skatelab.capture.proto.Imu.IMURecordOrBuilder {
      // Construct using ru.skatelab.capture.proto.Imu.IMURecord.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public RecordCase
          getRecordCase() {
        return instance.getRecordCase();
      }

      public Builder clearRecord() {
        copyOnWrite();
        instance.clearRecord();
        return this;
      }


      /**
       * <code>.skatelab.capture.IMUSample sample = 1;</code>
       */
      @java.lang.Override
      public boolean hasSample() {
        return instance.hasSample();
      }
      /**
       * <code>.skatelab.capture.IMUSample sample = 1;</code>
       */
      @java.lang.Override
      public ru.skatelab.capture.proto.Imu.IMUSample getSample() {
        return instance.getSample();
      }
      /**
       * <code>.skatelab.capture.IMUSample sample = 1;</code>
       */
      public Builder setSample(ru.skatelab.capture.proto.Imu.IMUSample value) {
        copyOnWrite();
        instance.setSample(value);
        return this;
      }
      /**
       * <code>.skatelab.capture.IMUSample sample = 1;</code>
       */
      public Builder setSample(
          ru.skatelab.capture.proto.Imu.IMUSample.Builder builderForValue) {
        copyOnWrite();
        instance.setSample(builderForValue.build());
        return this;
      }
      /**
       * <code>.skatelab.capture.IMUSample sample = 1;</code>
       */
      public Builder mergeSample(ru.skatelab.capture.proto.Imu.IMUSample value) {
        copyOnWrite();
        instance.mergeSample(value);
        return this;
      }
      /**
       * <code>.skatelab.capture.IMUSample sample = 1;</code>
       */
      public Builder clearSample() {
        copyOnWrite();
        instance.clearSample();
        return this;
      }

      /**
       * <code>.skatelab.capture.IMUGap gap = 2;</code>
       */
      @java.lang.Override
      public boolean hasGap() {
        return instance.hasGap();
      }
      /**
       * <code>.skatelab.capture.IMUGap gap = 2;</code>
       */
      @java.lang.Override
      public ru.skatelab.capture.proto.Imu.IMUGap getGap() {
        return instance.getGap();
      }
      /**
       * <code>.skatelab.capture.IMUGap gap = 2;</code>
       */
      public Builder setGap(ru.skatelab.capture.proto.Imu.IMUGap value) {
        copyOnWrite();
        instance.setGap(value);
        return this;
      }
      /**
       * <code>.skatelab.capture.IMUGap gap = 2;</code>
       */
      public Builder setGap(
          ru.skatelab.capture.proto.Imu.IMUGap.Builder builderForValue) {
        copyOnWrite();
        instance.setGap(builderForValue.build());
        return this;
      }
      /**
       * <code>.skatelab.capture.IMUGap gap = 2;</code>
       */
      public Builder mergeGap(ru.skatelab.capture.proto.Imu.IMUGap value) {
        copyOnWrite();
        instance.mergeGap(value);
        return this;
      }
      /**
       * <code>.skatelab.capture.IMUGap gap = 2;</code>
       */
      public Builder clearGap() {
        copyOnWrite();
        instance.clearGap();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:skatelab.capture.IMURecord)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ru.skatelab.capture.proto.Imu.IMURecord();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "record_",
              "recordCase_",
              ru.skatelab.capture.proto.Imu.IMUSample.class,
              ru.skatelab.capture.proto.Imu.IMUGap.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002<" +
                "\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ru.skatelab.capture.proto.Imu.IMURecord> parser = PARSER;
          if (parser == null) {
            synchronized (ru.skatelab.capture.proto.Imu.IMURecord.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ru.skatelab.capture.proto.Imu.IMURecord>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:skatelab.capture.IMURecord)
    private static final ru.skatelab.capture.proto.Imu.IMURecord DEFAULT_INSTANCE;
    static {
      IMURecord defaultInstance = new IMURecord();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IMURecord.class, defaultInstance);
    }

    public static ru.skatelab.capture.proto.Imu.IMURecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMURecord> PARSER;

    public static com.google.protobuf.Parser<IMURecord> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
