[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1280x800x24 -ac
autorestart=true

[program:emulator]
command=/opt/android-sdk/emulator/emulator @skatelab -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -accel on
environment=DISPLAY=":0"
autorestart=true
startsecs=60

[program:adb-server]
command=/opt/android-sdk/platform-tools/adb wait-for-device
autorestart=true

[program:websockify]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5900
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -forever -shared -rfbport 5900 -nopw
environment=DISPLAY=":0"
autorestart=true
