[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:emulator]
command=/opt/android-sdk/emulator/emulator @skatelab -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -accel on -prop ro.adb.secure=0
autorestart=true
startsecs=60

[program:adb-server]
command=/opt/android-sdk/platform-tools/adb -a nodaemon server start
autorestart=true
startsecs=5