coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

flags:
  shared:
    paths:
      - mobile/shared/
  android:
    paths:
      - mobile/androidApp/

comment:
  layout: "diff, flags, files"
  behavior: default