syntax = "proto3";

package skatelab.capture;

option java_package = "ru.skatelab.capture.proto";

message IMUSample {
  uint64 timestamp_ns = 1;
  float acc_x = 2;
  float acc_y = 3;
  float acc_z = 4;
  float gyro_x = 5;
  float gyro_y = 6;
  float gyro_z = 7;
  float quat_w = 8;
  float quat_x = 9;
  float quat_y = 10;
  float quat_z = 11;
}

message IMUGap {
  uint64 last_sample_ns = 1;
  uint64 first_sample_ns = 2;
  uint32 reconnect_seq = 3;
}

message IMURecord {
  oneof record {
    IMUSample sample = 1;
    IMUGap gap = 2;
  }
}
