name: 'Setup Android SDK + Gradle'
description: 'JDK 17 + Android SDK + Gradle cache'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false