"""RED→GREEN contract — auth.py /resend-verification must use a dedicated
create_verification_token() function, NOT create_password_reset_token().

Bug: Line 406 in routes/auth.py calls `create_password_reset_token()` in the
/resend-verification endpoint. The CRUD function `create_verification_token_crud`
correctly stores the token in the verification_tokens table, but the token VALUE
is generated by `create_password_reset_token()` — a function named for a different
purpose. Currently both `create_password_reset_token()` and the non-existent
`create_verification_token()` are identical (`secrets.token_hex(32)`), so this
doesn't crash. But it's a semantic mismatch that would break if token generators
ever diverge (e.g., adding a prefix like "vr_" for verification vs "pr_" for
password reset, or using different lengths).

Issue: Wrong function name called for email verification token generation.
"""

from pathlib import Path

from app.auth import security
from app.auth.security import create_password_reset_token


def test_create_verification_token_function_exists():
    """A dedicated create_verification_token() must exist in auth/security.py.

    Pre-fix: only create_password_reset_token() and create_refresh_token()
    exist. The verification endpoint reused the password-reset one.
    Post-fix: create_verification_token() is a separate function.
    """
    assert hasattr(security, "create_verification_token"), (
        "create_verification_token() must exist in auth/security.py — "
        "/resend-verification should not reuse create_password_reset_token()"
    )


def test_resend_verification_uses_dedicated_verification_function():
    """/resend-verification must use create_verification_token(), NOT
    create_password_reset_token()."""
    auth_path = Path(__file__).resolve().parents[2] / "app" / "routes" / "auth.py"
    source = auth_path.read_text()
    # Post-fix: the verification endpoint (line ~406) calls
    # create_verification_token(), not create_password_reset_token().
    assert "create_verification_token()" in source, (
        "Expected create_verification_token() call in auth.py for /resend-verification"
    )
    # Pre-fix had: "create_password_reset_token()" called twice
    # (password reset + verification). Post-fix: once (password reset only).
    count = source.count("create_password_reset_token()")
    assert count == 1, (
        f"create_password_reset_token() should be called exactly once "
        f"(password reset only), found {count} — /resend-verification "
        f"must use create_verification_token() instead"
    )


def test_verification_token_produces_hex():
    """create_verification_token() must produce a hex string token.

    Same shape as create_password_reset_token() (secrets.token_hex(32)) but
    a separate function so they can diverge in the future.
    """
    create_verification_token = security.create_verification_token  # noqa: F841
    token1 = create_verification_token()
    token2 = create_verification_token()
    assert len(token1) == 64, f"Expected 64-char hex token, got {len(token1)}"
    assert token1 != token2, "Consecutive tokens should differ"
    assert all(c in "0123456789abcdef" for c in token1), "Token should be hex"


def test_password_reset_function_unaffected():
    """The password-reset token function still works (regression)."""
    token = create_password_reset_token()
    assert len(token) == 64
    assert all(c in "0123456789abcdef" for c in token)
