[Interface]
PrivateKey = QBGWAKnIe8+ciOauXIzwmRXLff54QhO+/CLoC7iDhFM=
Address = 10.99.0.2/24
# AWG obfuscation (must match on all peers)
Jc = 4
Jmin = 64
Jmax = 256
S1 = 10
S2 = 15
S3 = 8
S4 = 0
H1 = 100000-200000
H2 = 300000-350000
H3 = 400000-450000
H4 = 500000-550000

[Peer]
PublicKey = bgEzalcpiTsmVhT1VvoIKnTi7KJs26tuwAHMBxspcks=
PresharedKey = X6Mp9m3Az1kIyRaqeZ/h93gR6njXkE5ke8ZzBmxZujY=
Endpoint = 176.9.0.156:51820
AllowedIPs = 10.99.0.0/24
PersistentKeepalive = 25
